# This is a basic workflow to help you get started with Actions

name: Create Renovate Data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Download recent extensions
        run: |
          .\01-update-extension-cache.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        shell: pwsh 
        
      - name: Generate azure-pipelines-marketplace-tasks.json
        run: |
          .\02-generate-renovate-data-marketplace.ps1
        shell: pwsh 

      - name: Generate azure-pipelines-builtin-tasks.json
        run: |
          .\03-generate-renovate-data-builtin.ps1
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        shell: pwsh
