name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
